// ── SillyImage Lab 主面板骨架 ──
import { slLog } from '../log.js';
import { CAT, applyTheme, injectThemeStyle } from './theme.js';
import { settings, saveSettings } from '../settings.js';
import * as tabs from './tabs.js';
import * as compact from './compact-bar.js';

var _panelEl = null, _expandedVisible = false;

export function getPanelEl() { return _panelEl; }
export function createExpandedPanel() {
  if (_panelEl) return;
  var isM = window.innerWidth < 600, ps = "position:fixed;z-index:10000;background:" + CAT.bg + ";border-radius:" + CAT.radius + ";box-shadow:0 4px 32px rgba(0,0,0,0.2);border:" + CAT.borderStyle + " " + CAT.line + ";font-family:" + CAT.font + ";color:" + CAT.text + ";display:none;flex-direction:column;overflow:hidden;";
  ps += isM ? "bottom:0;left:0;right:0;height:70vh;border-radius:18px 18px 0 0;" : "width:540px;height:80vh;top:50%;left:50%;transform:translate(-50%,-50%);";
  var h = '<div id="sl_panel" style="' + ps + '">';
  h += '<div id="sl_panel_header" style="position:relative;padding:14px 20px 10px;display:flex;align-items:center;justify-content:center;border-bottom:1px solid ' + CAT.line + ';cursor:move;flex-shrink:0;"><div style="display:flex;align-items:center;gap:10px;pointer-events:none;"><span style="font-size:26px;">=^_^=</span><div><div style="font-weight:700;font-size:15px;color:' + CAT.text + ';">偷懒小猫</div><div style="font-size:9px;color:' + CAT.sub + ';">SillyImage Lab v2.3</div></div></div><button id="sl_close_panel" style="position:absolute;right:14px;top:50%;transform:translateY(-50%);border:none;background:none;cursor:pointer;font-size:18px;color:' + CAT.mute + ';padding:4px 8px;">✕</button><button id="sl_btn_log" style="position:absolute;right:40px;top:50%;transform:translateY(-50%);border:none;background:none;cursor:pointer;font-size:14px;color:' + CAT.mute + ';padding:4px 6px;">📋</button></div>';
  h += '<div id="sl_panel_body" style="flex:1;overflow-y:scroll;padding:16px 18px;min-height:0;"></div>';
  h += '<div id="sl_panel_tabs" style="display:flex;border-top:1px solid ' + CAT.line + ';flex-shrink:0;"><button class="sl_tab_btn active" data-tab="home" style="flex:1;padding:12px;border:none;background:none;cursor:pointer;font-size:13px;color:' + CAT.accent + ';font-weight:600;border-top:2px solid ' + CAT.accent + ';margin-top:-1px;">🏠 首页</button><button class="sl_tab_btn" data-tab="settings" style="flex:1;padding:12px;border:none;background:none;cursor:pointer;font-size:13px;color:' + CAT.sub + ';font-weight:400;">⚙️ 设置</button><button class="sl_tab_btn" data-tab="archive" style="flex:1;padding:12px;border:none;background:none;cursor:pointer;font-size:13px;color:' + CAT.sub + ';font-weight:400;">📋 档案</button></div></div>';
  _panelEl = jQuery(h).appendTo("body");
  _panelEl.on("click", ".sl_tab_btn", function () { var tab = jQuery(this).data("tab"); _panelEl.find(".sl_tab_btn").removeClass("active").css({ color: CAT.sub, fontWeight: "400", borderTopColor: "transparent" }); jQuery(this).addClass("active").css({ color: CAT.accent, fontWeight: "600", borderTopColor: CAT.accent }); if (tab === "home") tabs.renderHomeTab(); else if (tab === "settings") tabs.renderSettingsTab(); else tabs.renderArchiveTab(); });
  jQuery("#sl_close_panel").on("click", function (e) { e.stopPropagation(); hidePanel(); });
  jQuery("#sl_btn_log").on("click", function (e) { e.stopPropagation(); tabs.showLogViewer(); });
  if (!isM) { (function () { var dragging = false, sx, sy, px, py; jQuery("#sl_panel_header").on("mousedown", function (e) { if (jQuery(e.target).closest("button").length) return; dragging = true; sx = e.clientX; sy = e.clientY; var o = _panelEl.offset(); px = o.left; py = o.top; _panelEl.css({ left: px + "px", top: py + "px", right: "auto", bottom: "auto", transform: "none" }); }); jQuery(document).on("mousemove", function (e) { if (!dragging) return; _panelEl.css({ left: (px + e.clientX - sx) + "px", top: (py + e.clientY - sy) + "px" }); }).on("mouseup", function () { dragging = false; }); })(); }
}
export function togglePanel() { if (!_panelEl) createExpandedPanel(); _expandedVisible ? hidePanel() : showPanel(); }
export function showPanel() { if (!_panelEl) createExpandedPanel(); _expandedVisible = true; applyTheme(settings.uiTheme || '奶糖小猫'); _panelEl.css({ left: "50%", top: "50%", right: "auto", bottom: "auto", transform: "translate(-50%,-50%)", maxHeight: "80vh", height: "80vh", width: "540px", flexDirection: "column" }); _panelEl.fadeIn(200, function () { _panelEl.css("display", "flex"); }); var _ce2 = compact.getCompactEl(); if (_ce2) _ce2.hide(); tabs.renderHomeTab(); }
export function hidePanel() { _expandedVisible = false; if (_panelEl) _panelEl.hide(); var _ce = compact.getCompactEl(); if (_ce) _ce.show(); compact.refreshCompactBar(); }
export function buildUI(extSettings) { slLog("=^_^= UI v2.3 start"); var knownThemes=["奶糖小猫","贴纸小猫","云朵猫窝","像素小猫"]; if(settings.uiTheme && knownThemes.indexOf(settings.uiTheme)===-1){ settings.uiTheme="奶糖小猫"; try{saveSettings();}catch(e){} } applyTheme(settings.uiTheme||"奶糖小猫"); if(!document.getElementById("sl_global_style")){var s=document.createElement("style");s.id="sl_global_style";s.textContent="#sl_compact,#sl_panel{font-family:var(--sl-font)!important}#sl_compact button,#sl_panel button{transition:all 0.2s cubic-bezier(0.34,1.56,0.64,1)!important}#sl_compact button:hover,#sl_panel button:hover{filter:brightness(0.92);transform:translateY(-1px)}#sl_compact button:active,#sl_panel button:active{transform:translateY(0) scale(0.97)}#sl_panel input,#sl_panel select,#sl_panel textarea{border-radius:var(--sl-radius)!important;border:var(--sl-border)!important;background:var(--sl-card)!important;color:var(--sl-text)!important}#sl_panel input:focus,#sl_panel select:focus,#sl_panel textarea:focus{border-color:var(--sl-accent)!important;box-shadow:0 0 0 3px rgba(99,102,241,0.1)!important}#sl_panel .sl_tab_btn{transition:all 0.2s ease!important}";document.head.appendChild(s);} compact.createCompactBar(); createExpandedPanel(); injectThemeStyle(); }