// ── SillyImage Lab 子面板（AI 助理 / ComfyUI / 高级选项） ──
import { CAT } from './theme.js';
import { toast, esc, escAttr, sbtn, fi } from './utils.js';
import { settings, saveSettings, getSTHeaders } from '../settings.js';
import { STYLE_PRESETS } from '../comfyui.js';
export function openSubPanel(type) {
  var h = '<div id="sl_sub_panel" style="position:absolute;top:0;left:0;right:0;bottom:0;background:' + CAT.bg + ';display:flex;flex-direction:column;z-index:10;border-radius:' + CAT.radius + ';transform:scale(0.5);opacity:0;transition:transform .15s ease-out,opacity .15s ease-out;">';
  h += '<div style="display:flex;align-items:center;justify-content:space-between;padding:12px 16px;border-bottom:1px solid ' + CAT.line + ';flex-shrink:0;"><button class="sl_close_sub" style="border:none;background:none;cursor:pointer;font-size:16px;color:' + CAT.accent + ';font-weight:600;">← 返回</button><span style="font-weight:700;font-size:13px;color:' + CAT.text + ';"></span><span></span></div><div id="sl_sub_body" style="flex:1;overflow-y:auto;padding:14px 16px;"></div></div>';
  var sub = jQuery(h).appendTo("#sl_panel"); jQuery(".sl_close_sub").on("click", function () { closeSubPanel(sub); }); fillSubPanel(type, jQuery("#sl_sub_body"));
  requestAnimationFrame(function () { sub.css({ transform: "scale(1)", opacity: "1" }); });
}
export function closeSubPanel(sub) { sub.css({ transform: "scale(0.5)", opacity: "0", transition: "transform .1s ease-in,opacity .1s ease-in" }); setTimeout(function () { sub.remove(); }, 120); }
export function fillSubPanel(type, body) {
  var f = fi();
  if (type === "aux") {
    var h = '<div style="margin-bottom:8px;"><div style="font-size:11px;color:' + CAT.sub + ';margin-bottom:2px;">AI 提供商</div><select id="sl_aux_provider" style="' + f + '"><option value="deepseek"' + (settings.auxProvider === "deepseek" ? " selected" : "") + '>DeepSeek</option><option value="custom"' + (settings.auxProvider === "custom" ? " selected" : "") + ">自定义</option></select></div>";
    h += '<div style="margin-bottom:8px;"><div style="font-size:11px;color:' + CAT.sub + ';margin-bottom:2px;">API 地址</div><input id="sl_aux_url" type="text" value="' + escAttr(settings.auxUrl || "") + '" style="' + f + '"></div>';
    h += '<div style="margin-bottom:8px;"><div style="font-size:11px;color:' + CAT.sub + ';margin-bottom:2px;">API Key</div><input id="sl_aux_key" type="password" value="' + escAttr(settings.auxKey || "") + '" style="' + f + '"></div>';
    h += '<div style="margin-bottom:8px;"><div style="font-size:11px;color:' + CAT.sub + ';margin-bottom:2px;">聊天分析模型</div><input id="sl_aux_model" type="text" value="' + escAttr(settings.auxModel || "") + '" style="' + f + '"></div>';
    h += '<div style="margin-bottom:8px;"><div style="font-size:11px;color:' + CAT.sub + ';margin-bottom:2px;">角色卡分析模型</div><input id="sl_profile_model" type="text" value="' + escAttr(settings.profileModel || "") + '" style="' + f + '"></div>';
    h += '<div style="display:flex;gap:8px;align-items:center;"><button id="sl_test_aux" style="' + sbtn(CAT.accent) + '">🔌 测试连接</button><span id="sl_aux_status" style="font-size:11px;color:' + CAT.sub + ';"></span></div>';
    body.html(h);
    jQuery("#sl_aux_provider").on("change", function () { settings.auxProvider = jQuery(this).val(); saveSettings(); });
    jQuery("#sl_aux_url").on("change input", function () { settings.auxUrl = jQuery(this).val(); saveSettings(); });
    jQuery("#sl_aux_key").on("change input", function () { settings.auxKey = jQuery(this).val(); saveSettings(); });
    jQuery("#sl_aux_model").on("change input", function () { settings.auxModel = jQuery(this).val(); saveSettings(); });
    jQuery("#sl_profile_model").on("change input", function () { settings.profileModel = jQuery(this).val(); saveSettings(); });
    jQuery("#sl_test_aux").on("click", async function () { var b = jQuery(this), s = jQuery("#sl_aux_status"); b.prop("disabled", true).text("测试中..."); try { var url = (jQuery("#sl_aux_url").val() || "").replace(/\/+$/, "") + "/chat/completions", key = jQuery("#sl_aux_key").val(), hd = { "Content-Type": "application/json" }; if (key) hd["Authorization"] = "Bearer " + key; var r = await fetch(url, { method: "POST", headers: hd, body: JSON.stringify({ model: jQuery("#sl_aux_model").val() || "default", messages: [{ role: "user", content: "hi" }], max_tokens: 3, stream: false }) }); if (r.ok) { s.css({ color: CAT.green }).text("连接成功喵~ ✨"); toast("success", "AI助理连接成功~"); } else { var t = await r.text().catch(function () { return ""; }); s.css({ color: CAT.red }).text("HTTP " + r.status); toast("error", "连接失败: " + r.status); } } catch (e) { s.css({ color: CAT.red }).text(e.message); toast("error", "连不上喵…"); } b.prop("disabled", false).text("🔌 测试连接"); });
  } else if (type === "comfy") {
    var h = '<div style="margin-bottom:8px;"><div style="font-size:11px;color:' + CAT.sub + ';margin-bottom:2px;">ComfyUI 地址</div><input id="sl_comfy_url" type="text" value="' + escAttr(settings.cUrl || "http://localhost:8181") + '" style="' + f + '"></div>';
    h += '<div style="display:flex;gap:8px;align-items:center;margin-bottom:8px;"><button id="sl_test_comfy" style="' + sbtn(CAT.accent) + '">🔌 测试连接</button><span id="sl_comfy_status" style="font-size:11px;color:' + CAT.sub + ';"></span></div>';
    h += '<div style="display:flex;gap:6px;align-items:center;margin-bottom:6px;"><input id="sl_wf_name" type="text" value="' + escAttr(settings.cWfName || "") + '" placeholder="工作流名称（可选）" style="flex:1;padding:6px 8px;border:1px solid ' + CAT.line + ';border-radius:6px;font-size:11px;background:' + CAT.card + ';color:' + CAT.text + ';"></div>';
    h += '<div style="display:flex;gap:4px;margin-bottom:4px;"><button id="sl_wf_load" style="' + sbtn(CAT.sub) + 'font-size:10px;">📂 加载</button><button id="sl_wf_save_as" style="' + sbtn(CAT.green) + 'font-size:10px;">💾 另存</button><button id="sl_wf_del" style="' + sbtn(CAT.red) + 'font-size:10px;">🗑 删除</button></div>';
    h += '<div style="font-size:11px;color:' + CAT.sub + ';margin-bottom:2px;">工作流 JSON</div><textarea id="sl_comfy_wf" rows="5" style="width:100%;padding:8px;border:1px solid ' + CAT.line + ';border-radius:8px;background:' + CAT.card + ';font-family:monospace;font-size:11px;color:' + CAT.text + ';resize:vertical;box-sizing:border-box;">' + esc(settings.cWf || "") + "</textarea>";
    h += '<div style="display:flex;gap:6px;margin:6px 0;"><button id="sl_wf_import_btn" style="' + sbtn(CAT.sub) + 'font-size:10px;">📁 导入JSON</button><input type="file" id="sl_wf_import" accept=".json" style="display:none;"><button id="sl_analyze_wf" style="' + sbtn(CAT.accent) + '">🔍 解析节点</button><button id="sl_save_wf" style="' + sbtn(CAT.green) + '">💾 保存工作流</button></div>';
    h += '<div id="sl_node_list" style="font-size:10px;color:' + CAT.sub + ';max-height:200px;overflow-y:auto;margin-bottom:8px;"></div>';
    h += '<div style="font-size:11px;color:' + CAT.sub + ';margin-bottom:4px;">画风预设</div><select id="sl_style_preset" style="' + f + 'margin-bottom:8px;"><option value="">不使用预设</option>';
    for (var sk in STYLE_PRESETS) if (sk) h += '<option value="' + escAttr(sk) + '"' + (settings.stylePreset === sk ? " selected" : "") + ">" + esc(sk) + "</option>";
    h += "</select>";
    h += '<div style="font-size:11px;color:' + CAT.sub + ';margin-bottom:2px;">负面提示词</div><input id="sl_neg" type="text" value="' + escAttr(settings.neg || "") + '" style="' + f + '" placeholder="worst quality, lowres...">';
    body.html(h);
    jQuery("#sl_comfy_url").on("change input", function () { settings.cUrl = jQuery(this).val(); saveSettings(); });
    jQuery("#sl_test_comfy").on("click", async function () { var b = jQuery(this), s = jQuery("#sl_comfy_status"); b.prop("disabled", true).text("测试中..."); try { var r = await fetch("/api/sd/comfy/ping", { method: "POST", headers: Object.assign({ "Content-Type": "application/json" }, getSTHeaders()), body: JSON.stringify({ url: jQuery("#sl_comfy_url").val() }) }); if (r.ok) { var d = await r.json().catch(function () { return {}; }); s.css({ color: CAT.green }).text("已连接" + (d.device ? " (" + d.device + ")" : "")); toast("success", "ComfyUI 连上啦~ ✨"); } else { var txt = await r.text().catch(function () { return ""; }); s.css({ color: CAT.red }).text("HTTP " + r.status); toast("error", "连接失败喵~"); } } catch (e) { s.css({ color: CAT.red }).text("连不上"); toast("error", "连不上喵…"); } b.prop("disabled", false).text("🔌 测试连接"); });
    jQuery("#sl_analyze_wf").on("click", function () {
      var raw = jQuery("#sl_comfy_wf").val(); if (!raw) { toast("info", "请先粘贴工作流 JSON 喵~"); return; }
      try { var wf = JSON.parse(raw), nodes = [], params = {}; for (var nid in wf) { var nd = wf[nid]; if (!nd || !nd.class_type) continue; nodes.push(nd.class_type); if (/KSampler/i.test(nd.class_type) && nd.inputs) { if (nd.inputs.steps != null) params.steps = nd.inputs.steps; if (nd.inputs.cfg != null) params.cfg = nd.inputs.cfg; if (nd.inputs.seed != null) params.seed = nd.inputs.seed; if (nd.inputs.denoise != null) params.denoise = nd.inputs.denoise; } if (/EmptyLatent|Latent/i.test(nd.class_type) && nd.inputs) { if (nd.inputs.width != null) params.width = nd.inputs.width; if (nd.inputs.height != null) params.height = nd.inputs.height; if (nd.inputs.batch_size != null) params.batch = nd.inputs.batch_size; } }
        var nh = '<span style="color:' + CAT.green + ';">✅ ' + nodes.length + " 个节点：</span> " + nodes.map(function (n) { return '<span style="display:inline-block;background:' + CAT.bg + ';padding:1px 6px;border-radius:3px;margin:1px;font-size:9px;">' + n + "</span>"; }).join(" "), ph = "", pk = Object.keys(params);
        if (pk.length) { var labels = { steps: "步数", cfg: "CFG", seed: "种子", denoise: "降噪", width: "宽度", height: "高度", batch: "批次" }; ph += '<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px;margin-top:6px;">'; for (var pi = 0; pi < pk.length; pi++) { var k = pk[pi], v = params[k]; ph += '<div><div style="font-size:10px;color:' + CAT.sub + ';margin-bottom:2px;">' + esc(labels[k] || k) + '</div><input class="sl_wf_param" data-pk="' + escAttr(k) + '" value="' + escAttr(v) + '" style="width:100%;padding:6px 8px;border:1px solid ' + CAT.line + ';border-radius:6px;font-size:12px;background:' + CAT.card + ';color:' + CAT.text + ';box-sizing:border-box;"></div>'; } ph += "</div>"; } else ph = '<div style="font-size:10px;color:' + CAT.mute + ';margin-top:4px;">没有可编辑参数喵~</div>';
        jQuery("#sl_node_list").html(nh + ph);
        jQuery(".sl_wf_param").off("change input").on("change input", function () { try { var raw2 = jQuery("#sl_comfy_wf").val(), wf2 = JSON.parse(raw2), pk2 = jQuery(this).data("pk"), nv = jQuery(this).val(); for (var nid2 in wf2) { var nd2 = wf2[nid2]; if (!nd2 || !nd2.inputs) continue; var cmap = { steps: /KSampler/i, cfg: /KSampler/i, seed: /KSampler/i, denoise: /KSampler/i, width: /EmptyLatent|Latent/i, height: /EmptyLatent|Latent/i, batch: /EmptyLatent|Latent/i }; if (cmap[pk2] && cmap[pk2].test(nd2.class_type) && nd2.inputs[pk2] != null) { nd2.inputs[pk2] = /^\d+$/.test(nv) ? parseInt(nv) : (/^\d+\.\d+$/.test(nv) ? parseFloat(nv) : nv); break; } } jQuery("#sl_comfy_wf").val(JSON.stringify(wf2)); settings.cWf = JSON.stringify(wf2); saveSettings(); } catch (e) { } });
      } catch (e) { jQuery("#sl_node_list").html('<span style="color:' + CAT.red + ';">❌ JSON 格式错误喵~</span>'); }
    });
    jQuery("#sl_save_wf").on("click", function () { var raw = jQuery("#sl_comfy_wf").val(); if (!raw) return; try { JSON.parse(raw); settings.cWf = raw; saveSettings(); toast("success", "工作流保存好啦喵~ ✨"); } catch (e) { toast("error", "JSON 格式不对喵…"); } });
    if (!settings.workflows) settings.workflows = {};
    jQuery("#sl_wf_save_as").on("click", function () { var n = jQuery("#sl_wf_name").val() || ("wf_" + Date.now()); settings.workflows[n] = jQuery("#sl_comfy_wf").val(); settings.cWfName = n; saveSettings(); toast("success", "已保存: " + n); });
    jQuery("#sl_wf_load").on("click", function () { var n = jQuery("#sl_wf_name").val(); if (settings.workflows[n]) { jQuery("#sl_comfy_wf").val(settings.workflows[n]); toast("success", "已加载: " + n); } else toast("info", "输入名称后点加载喵~"); });
    jQuery("#sl_wf_del").on("click", function () { var n = jQuery("#sl_wf_name").val(); if (settings.workflows[n]) { delete settings.workflows[n]; saveSettings(); toast("success", "已删除: " + n); } });
    jQuery("#sl_wf_import_btn").on("click", function () { jQuery("#sl_wf_import").trigger("click"); });
    jQuery("#sl_wf_import").on("change", function () { var file = this.files[0]; if (!file) return; var reader = new FileReader(); reader.onload = function (e) { jQuery("#sl_comfy_wf").val(e.target.result); toast("success", "导入成功喵~ ✨"); }; reader.readAsText(file); });
    jQuery("#sl_style_preset").on("change", function () { settings.stylePreset = jQuery(this).val(); saveSettings(); });
    jQuery("#sl_neg").on("change input", function () { settings.neg = jQuery(this).val(); saveSettings(); });
  } else if (type === "advanced") {
    var h = '<div style="background:' + CAT.card + ';border-radius:10px;padding:12px;margin-bottom:8px;border:1px solid ' + CAT.line + ';">';
    h += '<label style="display:flex;align-items:center;gap:8px;cursor:pointer;"><input type="checkbox" id="sl_nsfw"' + (settings.nsfwEnhance ? " checked" : "") + '><span style="font-size:12px;color:' + CAT.text + ';">🔞 NSFW 增强模式</span></label>';
    h += '<div style="margin-top:8px;"><label style="display:flex;align-items:center;gap:8px;cursor:pointer;"><input type="radio" name="sl_story" value="narrative"' + (settings.storyMode !== "comic" ? " checked" : "") + '><span style="font-size:12px;color:' + CAT.text + ';">📖 叙事模式</span></label></div><div><label style="display:flex;align-items:center;gap:8px;cursor:pointer;"><input type="radio" name="sl_story" value="comic"' + (settings.storyMode === "comic" ? " checked" : "") + '><span style="font-size:12px;color:' + CAT.text + ';">📱 漫画模式</span></label></div></div>';
    h += '<div style="background:' + CAT.card + ';border-radius:10px;padding:12px;border:1px solid ' + CAT.line + ';">';
    h += '<label style="display:flex;align-items:center;gap:8px;cursor:pointer;"><input type="checkbox" id="sl_debug"' + (settings.debugMode ? " checked" : "") + '><span style="font-size:12px;color:' + CAT.text + ';">🐛 Debug 模式</span></label></div>';
    body.html(h);
    jQuery("#sl_nsfw").on("change", function () { settings.nsfwEnhance = jQuery(this).is(":checked"); saveSettings(); });
    jQuery("input[name=sl_story]").on("change", function () { settings.storyMode = jQuery(this).val(); saveSettings(); });
    jQuery("#sl_debug").on("change", function () { settings.debugMode = jQuery(this).is(":checked"); saveSettings(); });
  }
}